[login info]
url = https://saucedemo.com/
username = standard_user
password = secret_sauce
locked_out_user = locked_out_user
invalid_user = Test
;url = https://admin-demo.nopcommerce.com/admin/
;username = admin@yourstore.com
;password = admin